### ISSUE TITLE
HW7 fix request

### ISSUE THREAD

**Issue by pibion** [phys2331/idyll-material#16]
![image](https://user-images.githubusercontent.com/1872784/111795017-6ec2ef00-888c-11eb-8d9e-1b6dab4c45ca.png)

**Comment by drlmnop** [comment]
Replaced the location of segment center section to:

```
seg_vec_init = seg_vec * #_init
seg_vec_fin = seg_vec * #_fin
cent_seg = (seg_vec_init + seg_vec_fin)/2
```

where #_init and #_fin are the number of segments that create the bounds of the target segment.
